server:
  port: 8081

spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Request-Id, ${random.uuid}
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
