server:
  port: 8085

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/users"
    username: "postgres"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
  application:
    name: CATALOG-SERVICE
  config:
    import: optional:configserver:http://localhost:8082
