server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  logging:
    level:
      com.netflix.discovery: DEBUG
      org.springframework.cloud.netflix.eureka: DEBUG
